import { getServerSideSitemap } from "next-sitemap";
import { getStoreProducts } from "@/lib/products";
import { productSlug } from "@/lib/utils";

// Always resolve the current catalog fresh — a stale/cached product list here
// means new products silently never reach Google until this route happens to
// re-render, so don't let Next.js cache this route's data fetches.
export const dynamic = "force-dynamic";

export async function GET() {
  const baseUrl = process.env.SITE_URL || "https://veliova.com";

  // These also live in next-sitemap's static sitemap-0.xml (generated by the
  // "postbuild" script at build time) — but that generation step has proven
  // unreliable in production, so the two most important pages are duplicated
  // here in this always-fresh dynamic route as a safety net. Harmless if both
  // end up listing them; Google tolerates a URL appearing in more than one
  // sitemap.
  const staticFields = [
    { loc: `${baseUrl}/`, lastmod: new Date().toISOString(), changefreq: "daily" as const, priority: 1.0 },
    { loc: `${baseUrl}/shop`, lastmod: new Date().toISOString(), changefreq: "daily" as const, priority: 0.9 },
  ];

  try {
    // Provider-aware: includes both Printful and Printify products, whichever
    // the "pod_provider" setting currently has active (see src/lib/products.ts).
    const products = await getStoreProducts();
    const productFields = products.map((p) => ({
      loc: `${baseUrl}/shop/${productSlug(p.name, p.id)}`,
      lastmod: new Date().toISOString(),
      changefreq: "weekly" as const,
      priority: 0.8,
    }));
    return getServerSideSitemap([...staticFields, ...productFields]);
  } catch (err) {
    console.error("[server-sitemap.xml] Failed to build product sitemap:", err);
    return getServerSideSitemap(staticFields);
  }
}
