import type { MetadataRoute } from "next";

const SITE_URL = (process.env.SITE_URL || "https://veliova.com").replace(/\/$/, "");

/** Areas that are private, transactional, or have no crawlable content. */
const DISALLOW = [
  "/dashboard",
  "/account",
  "/auth",
  "/admin",
  "/api",
  "/checkout",
  "/cart",
];

/**
 * Paths under a disallowed prefix that must stay fetchable.
 *
 * Crawlers apply the longest matching rule, so a more specific `Allow` beats
 * the broader `Disallow: /api`. Pinterest requires catalog images to be
 * reachable by its user-agent, and the portrait renderer lives under /api.
 */
const ALLOW = ["/api/pinterest-image"];

/**
 * robots.txt, generated by Next.js rather than written to /public at build time.
 *
 * This used to be produced by next-sitemap's `postbuild` step, but that step
 * was not running on deploys, so the served file stayed frozen at an old
 * revision. Generating it here ties it to the normal build, so it can never
 * drift again.
 *
 * Google Merchant Center requires explicit `Googlebot` and `Googlebot-Image`
 * groups before it will run quality and policy checks on product pages.
 * Note that Google honours only the single most specific matching group, so
 * each group repeats the full disallow list rather than inheriting it.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "Googlebot",
        allow: ["/", ...ALLOW],
        disallow: DISALLOW,
      },
      {
        // Product images must be fetchable for listings to serve.
        userAgent: "Googlebot-Image",
        allow: "/",
      },
      {
        // Pinterest fetches both the catalog feed and every product image.
        userAgent: "Pinterest",
        allow: ["/", ...ALLOW],
        disallow: DISALLOW,
      },
      {
        userAgent: "*",
        allow: ["/", ...ALLOW],
        disallow: DISALLOW,
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
